name: example

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  fields_annotation:
    path: ../../annotation
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  fields:
    path: ../