name: fields_annotation
description: The annotation package for the fields generator. Generate all field names as Strings
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^2.4.0
