name: example

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  class_fields_annotation: ^0.1.0
  # class_fields_annotation:
  #   path: ../../class_fields_annotation
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  class_fields:
    path: ../

scripts: ../../../derry.yaml

import_sorter:
  comments: false
