builders:
  fields:
    import: "package:fields/fields.dart"
    builder_factories:
      - fieldsBuilder
    build_extensions:
      .dart:
        - class_fields.g.part
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
