builders:
  field_keys:
    import: "package:field_keys/field_keys.dart"
    builder_factories:
      - fieldKeysBuilder
    build_extensions:
      .dart:
        - .keys.dart
    auto_apply: dependents
    build_to: source