builders:
  fields:
    import: "package:fields/fields.dart"
    builder_factories:
      - fieldsBuilder
    build_extensions:
      .dart:
        - .f.dart
    auto_apply: dependents
    build_to: source