name: field_keys
description: Generate keys from field names to use within Maps
version: 0.0.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  analyzer: ^3.0.0
  build_config: ^1.0.0
  field_keys_annotation:
    path: ../annotation
  meta: ^1.7.0
  source_gen: ^1.2.1
  source_helper: ^1.3.1

dev_dependencies:
  generator_test:
    git: https://github.com/mrgnhnt96/generator_test
  json_annotation: ^4.4.0
  test: ^1.16.0
  very_good_analysis: ^2.4.0
