name: class_fields
description: Generate all field names as Strings to use within Maps, serialization, etc.
version: 0.1.0
repository: https://github.com/mrgnhnt96/class_fields/tree/master/packages/class_fields_generator
homepage: https://github.com/mrgnhnt96/class_fields

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  analyzer: ^3.1.0
  build: ^2.2.1
  build_config: ^1.0.0
  class_fields_annotation: ">=0.1.0 <0.2.0"
  # class_fields_annotation:
  #   path: ../class_fields_annotation
  meta: ^1.7.0
  source_gen: ^1.2.1
  source_helper: ^1.3.1

dev_dependencies:
  generator_test: ^0.1.0
  json_annotation: ^4.4.0
  test: ^1.16.0
  very_good_analysis: ^2.4.0

scripts: ../../derry.yaml

import_sorter:
  comments: false